# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/zytrams/.brew/Cellar/cmake/3.23.0/bin/cmake

# The command to remove a file.
RM = /Users/zytrams/.brew/Cellar/cmake/3.23.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zytrams/websrv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zytrams/websrv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/zytrams/.brew/Cellar/cmake/3.23.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/zytrams/.brew/Cellar/cmake/3.23.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zytrams/websrv/CMakeFiles /Users/zytrams/websrv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zytrams/websrv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named webserv

# Build rule for target.
webserv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webserv
.PHONY : webserv

# fast build rule for target.
webserv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/build
.PHONY : webserv/fast

srcs/Cluster.o: srcs/Cluster.cpp.o
.PHONY : srcs/Cluster.o

# target to build an object file
srcs/Cluster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/Cluster.cpp.o
.PHONY : srcs/Cluster.cpp.o

srcs/Cluster.i: srcs/Cluster.cpp.i
.PHONY : srcs/Cluster.i

# target to preprocess a source file
srcs/Cluster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/Cluster.cpp.i
.PHONY : srcs/Cluster.cpp.i

srcs/Cluster.s: srcs/Cluster.cpp.s
.PHONY : srcs/Cluster.s

# target to generate assembly for a file
srcs/Cluster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/Cluster.cpp.s
.PHONY : srcs/Cluster.cpp.s

srcs/HttpRequest.o: srcs/HttpRequest.cpp.o
.PHONY : srcs/HttpRequest.o

# target to build an object file
srcs/HttpRequest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/HttpRequest.cpp.o
.PHONY : srcs/HttpRequest.cpp.o

srcs/HttpRequest.i: srcs/HttpRequest.cpp.i
.PHONY : srcs/HttpRequest.i

# target to preprocess a source file
srcs/HttpRequest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/HttpRequest.cpp.i
.PHONY : srcs/HttpRequest.cpp.i

srcs/HttpRequest.s: srcs/HttpRequest.cpp.s
.PHONY : srcs/HttpRequest.s

# target to generate assembly for a file
srcs/HttpRequest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/HttpRequest.cpp.s
.PHONY : srcs/HttpRequest.cpp.s

srcs/IOSocket.o: srcs/IOSocket.cpp.o
.PHONY : srcs/IOSocket.o

# target to build an object file
srcs/IOSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/IOSocket.cpp.o
.PHONY : srcs/IOSocket.cpp.o

srcs/IOSocket.i: srcs/IOSocket.cpp.i
.PHONY : srcs/IOSocket.i

# target to preprocess a source file
srcs/IOSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/IOSocket.cpp.i
.PHONY : srcs/IOSocket.cpp.i

srcs/IOSocket.s: srcs/IOSocket.cpp.s
.PHONY : srcs/IOSocket.s

# target to generate assembly for a file
srcs/IOSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/IOSocket.cpp.s
.PHONY : srcs/IOSocket.cpp.s

srcs/PhysicalServer.o: srcs/PhysicalServer.cpp.o
.PHONY : srcs/PhysicalServer.o

# target to build an object file
srcs/PhysicalServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/PhysicalServer.cpp.o
.PHONY : srcs/PhysicalServer.cpp.o

srcs/PhysicalServer.i: srcs/PhysicalServer.cpp.i
.PHONY : srcs/PhysicalServer.i

# target to preprocess a source file
srcs/PhysicalServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/PhysicalServer.cpp.i
.PHONY : srcs/PhysicalServer.cpp.i

srcs/PhysicalServer.s: srcs/PhysicalServer.cpp.s
.PHONY : srcs/PhysicalServer.s

# target to generate assembly for a file
srcs/PhysicalServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/PhysicalServer.cpp.s
.PHONY : srcs/PhysicalServer.cpp.s

srcs/RequestBuilder.o: srcs/RequestBuilder.cpp.o
.PHONY : srcs/RequestBuilder.o

# target to build an object file
srcs/RequestBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/RequestBuilder.cpp.o
.PHONY : srcs/RequestBuilder.cpp.o

srcs/RequestBuilder.i: srcs/RequestBuilder.cpp.i
.PHONY : srcs/RequestBuilder.i

# target to preprocess a source file
srcs/RequestBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/RequestBuilder.cpp.i
.PHONY : srcs/RequestBuilder.cpp.i

srcs/RequestBuilder.s: srcs/RequestBuilder.cpp.s
.PHONY : srcs/RequestBuilder.s

# target to generate assembly for a file
srcs/RequestBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/RequestBuilder.cpp.s
.PHONY : srcs/RequestBuilder.cpp.s

srcs/SocketContainer.o: srcs/SocketContainer.cpp.o
.PHONY : srcs/SocketContainer.o

# target to build an object file
srcs/SocketContainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/SocketContainer.cpp.o
.PHONY : srcs/SocketContainer.cpp.o

srcs/SocketContainer.i: srcs/SocketContainer.cpp.i
.PHONY : srcs/SocketContainer.i

# target to preprocess a source file
srcs/SocketContainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/SocketContainer.cpp.i
.PHONY : srcs/SocketContainer.cpp.i

srcs/SocketContainer.s: srcs/SocketContainer.cpp.s
.PHONY : srcs/SocketContainer.s

# target to generate assembly for a file
srcs/SocketContainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/SocketContainer.cpp.s
.PHONY : srcs/SocketContainer.cpp.s

srcs/config/IConfig.o: srcs/config/IConfig.cpp.o
.PHONY : srcs/config/IConfig.o

# target to build an object file
srcs/config/IConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/IConfig.cpp.o
.PHONY : srcs/config/IConfig.cpp.o

srcs/config/IConfig.i: srcs/config/IConfig.cpp.i
.PHONY : srcs/config/IConfig.i

# target to preprocess a source file
srcs/config/IConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/IConfig.cpp.i
.PHONY : srcs/config/IConfig.cpp.i

srcs/config/IConfig.s: srcs/config/IConfig.cpp.s
.PHONY : srcs/config/IConfig.s

# target to generate assembly for a file
srcs/config/IConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/IConfig.cpp.s
.PHONY : srcs/config/IConfig.cpp.s

srcs/main.o: srcs/main.cpp.o
.PHONY : srcs/main.o

# target to build an object file
srcs/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/main.cpp.o
.PHONY : srcs/main.cpp.o

srcs/main.i: srcs/main.cpp.i
.PHONY : srcs/main.i

# target to preprocess a source file
srcs/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/main.cpp.i
.PHONY : srcs/main.cpp.i

srcs/main.s: srcs/main.cpp.s
.PHONY : srcs/main.s

# target to generate assembly for a file
srcs/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/main.cpp.s
.PHONY : srcs/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... webserv"
	@echo "... srcs/Cluster.o"
	@echo "... srcs/Cluster.i"
	@echo "... srcs/Cluster.s"
	@echo "... srcs/HttpRequest.o"
	@echo "... srcs/HttpRequest.i"
	@echo "... srcs/HttpRequest.s"
	@echo "... srcs/IOSocket.o"
	@echo "... srcs/IOSocket.i"
	@echo "... srcs/IOSocket.s"
	@echo "... srcs/PhysicalServer.o"
	@echo "... srcs/PhysicalServer.i"
	@echo "... srcs/PhysicalServer.s"
	@echo "... srcs/RequestBuilder.o"
	@echo "... srcs/RequestBuilder.i"
	@echo "... srcs/RequestBuilder.s"
	@echo "... srcs/SocketContainer.o"
	@echo "... srcs/SocketContainer.i"
	@echo "... srcs/SocketContainer.s"
	@echo "... srcs/config/IConfig.o"
	@echo "... srcs/config/IConfig.i"
	@echo "... srcs/config/IConfig.s"
	@echo "... srcs/main.o"
	@echo "... srcs/main.i"
	@echo "... srcs/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

